FROM openjdk:11
MAINTAINER Yash Yadav<yash.mlvt@gmail.com>
VOLUME /tmp
EXPOSE 8080
ARG JAR_FILE=target/social-app-1.0.0.jar
ADD ${JAR_FILE} social-app-1.0.0.jar
ENTRYPOINT ["java","-jar","/social-app-1.0.0.jar"]
